### ISSUE TITLE
Excellent project.

### ISSUE THREAD

**Issue by AMarcoVix** [jb3rndt/PersistentBottomNavBarV2#1]
Hi, all right, I'm from Brazil, I was happy to know that you are continuing to maintain the "Bilal Shahid13" project, great initiative. I'm new to flutter and I'm studying this project.
It uses multi-stack navigation, a question how to get a button on the Settings page, and by clicking change to the search stack. Did you get it. haha

My English is not good, so I used the translator.

**Comment by jb3rndt** [comment]
In this example Widget a `_controller` is specified for navigation:
```
class MyStackNavigation extends StatefulWidget {
  MyStackNavigation ({Key key}) : super(key: key);

  @override
  _MyStackNavigationState createState() => _MyStackNavigationState();
}

class _MyStackNavigationState extends State<MyStackNavigation> {
  PersistentTabController _controller;

  @override
  void initState() {
    super.initState();
    _controller = PersistentTabController(initialIndex: 0);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Stack Navigation Demo')),
      body: PersistentTabView(
        context,
        controller: _controller,
...
    );
  }
}
```
Then you can pass the `_controller` where you want and use `_controller.jumpToTab(i)` to jump to the search tab by clicking a button (i is the index of the search page).

I hope that helps :)
Otherwise, you can give me a code example or something

**Comment by timsntech** [comment]
hey, also much thanks from my side! great that you took the initiative to continue this nice project. much appreciated
