### ISSUE TITLE
how to refresh page in bottom bar menu when using stateManagement: true

### ISSUE THREAD

**Issue by Sang-Nguyen-25** [jb3rndt/PersistentBottomNavBarV2#10]
I'm having a problem with state Management: true. It doesn't update the page again, it only updates the first time and after that it keeps the state not updated.

```
body: PersistentTabView(
          context,
          controller: bottomTabcontroller,
          screens: pages,
          items: _navBarsItems(),
          confineInSafeArea: true,
          backgroundColor: Colors.white,
          handleAndroidBackButtonPress: true,
          resizeToAvoidBottomInset: true,
          stateManagement: true,
          hideNavigationBarWhenKeyboardShows: true,
          decoration: NavBarDecoration(
            borderRadius: BorderRadius.circular(10.0),
            colorBehindNavBar: Colors.white,
          ),
          popAllScreensOnTapOfSelectedTab: false,
          popActionScreens: PopActionScreensType.once,
          itemAnimationProperties: ItemAnimationProperties(
            duration: Duration(milliseconds: 200),
            curve: Curves.ease,
          ),
          screenTransitionAnimation: ScreenTransitionAnimation(
            animateTabTransition: true,
            curve: Curves.ease,
            duration: Duration(milliseconds: 200),
          ),
          navBarStyle: NavBarStyle.style6,
        )
```

**Comment by jb3rndt** [comment]
Sorry I couldnt reproduce your issue provided I understand it correctly. Can you provide you full code example and the output of `flutter doctor -v`?

**Comment by Sang-Nguyen-25** [comment]
Thanks for the help, i got it working calling the pageback from the navbar, to update the UI again.

**Comment by Abdelaty** [comment]
@Sang-Nguyen-25 can you help me with how did you do it?

**Comment by leossmith** [comment]
> Thanks for the help, i got it working calling the pageback from the navbar, to update the UI again.

Can you share a bit more info on this?

**Comment by ZahraVe** [comment]
@Abdelaty and @leossmith
You can update the state of your screen using your state management while keeping the PersistentTabView,          stateManagement: true.
