### ISSUE TITLE
showModalBottomSheet 

### ISSUE THREAD

**Issue by abdulrojakdev** [jb3rndt/PersistentBottomNavBarV2#100]
I'm using NavBarStyle 15, how do I when the badge is clicked show the Modal Bottom Sheet?

**Comment by jb3rndt** [comment]
In your `PersistentBottomNavBarItem` you can specify a `onPressed` method. Instead of switching to the page this callback will be executed. In there you can do `showModalBottomSheet()`.

```
PersistentBottomNavBarItem(
    icon: Icon(Icons.add),
    title: "Add",
    activeColorPrimary: Colors.blueAccent,
    activeColorSecondary: Colors.white,
    inactiveColorPrimary: Colors.white,
    onPressed: (context) {
      showModalBottomSheet(...);
    },
),
```
