### ISSUE TITLE
First screen appears on pressing back

### ISSUE THREAD

**Issue by itxmubi** [jb3rndt/PersistentBottomNavBarV2#104]
**Describe the bug**
Hi, I have 6 screens in the bottom nav bar, From any index except 0, when I click android back button, index 0 screen appears but selected item of bottom app bar not updated, on Pressing second-time android back buttom, Bottom nav bar  selected item updated to 0 index.

**To Reproduce**
1. Take 6 items and thier screens.
2. From bottom nav bar click on any bottom nav bar item except first
4. Click the android back button
5. First screen appears , but bottom nav bar item still showing that 3rd/4th screen is selected.

**Expected behavior**
Either it will not be navigated to first screen or if navigated , then nav bar item will be updated with android back button

**Comment by jb3rndt** [comment]
I followed your steps but sadly was not able to reproduce your issue. Can you post a minimal example that shows your behavior and tell the version of this package that you are using?

**Comment by itxmubi** [comment]
> I followed your steps but sadly was not able to reproduce your issue. Can you post a minimal example that shows your behavior and tell the version of this package that you are using?

Its fixed for me now , so i close this issue.

**Comment by KIA-AKIRA** [comment]
> > I followed your steps but sadly was not able to reproduce your issue. Can you post a minimal example that shows your behavior and tell the version of this package that you are using?
> 
> Its fixed for me now , It was not an issue in your code, so i close this issue.

how can you fixed it? i face with the same problem
