### ISSUE TITLE
Floating TabBar - Transparent BackgroundColor results in black

### ISSUE THREAD

**Issue by Yetispapa** [jb3rndt/PersistentBottomNavBarV2#106]
**Describe the bug**
The bug involves the tab bar's background color not appearing as expected when attempting to create a floating tab bar using the provided package.

**To Reproduce**
1.) Go to the app.
2.) Notice that the tabbar appears as a black background instead of transparent.

**Expected behavior**
I expected the tab bar to have a transparent background color so that it matches the background color of the current page.

**Screenshots**
this screenshot is from another package, but I intend to make the tab bar follow the Cupertino tabbar, which is why I'm utilizing your package. ;)
![184212839-57872c36-eeb9-40aa-ac3f-3b41b718c7a4](https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/15137276/9cdd15b4-ac8d-4ec8-95ba-c1779e66b1d2)

current status
![IMG_0438](https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/15137276/1471e036-3d60-46ae-b39c-aad88baa86aa)

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**

I'm using:

`persistent_bottom_nav_bar_v2: ^4.2.8`

I am attempting to achieve a floating tab bar using your package. To achieve this, I have set the following properties:

```
return PersistentTabView(
  context,
  navBarHeight: 56,
  margin: EdgeInsets.only(left: 24, right: 24, bottom: 8),
  screens: tabs.map((e) => e.site).toList(),
  items: tabs.asMap().entries.map(
    (MapEntry<int, MainTabBarSiteTab> e) {
      final int index = e.key;
      final MainTabBarSiteTab tab = e.value;
      final bool selected = selectedIndex == index;

      return PersistentBottomNavBarItem(
        icon: Icon(
          tab.icon,
          size: 20,
        ),
        activeColorPrimary: Colors.black,
        inactiveColorPrimary: Colors.grey,
      );
    },
  ).toList(),
  confineInSafeArea: true,
  backgroundColor: GlobalColors.white, // Default is Colors.white.
  handleAndroidBackButtonPress: true, // Default is true.
  resizeToAvoidBottomInset: true, // This needs to be true if you want to move up the screen when the keyboard appears. Default is true.
  stateManagement: true, // Default is true.
  hideNavigationBarWhenKeyboardShows: true, // Recommended to set 'resizeToAvoidBottomInset' as true while using this argument. Default is true.
  decoration: NavBarDecoration(
    colorBehindNavBar: Colors.transparent,
    adjustScreenBottomPaddingOnCurve: false,
    borderRadius: BorderRadius.all(Radius.circular(40)),
  ),
  popAllScreensOnTapOfSelectedTab: true,
  popActionScreens: PopActionScreensType.all,
  itemAnimationProperties: ItemAnimationProperties(
    // Navigation Bar's items animation properties.
    duration: Duration(milliseconds: 200),
    curve: Curves.ease,
  ),
  screenTransitionAnimation: ScreenTransitionAnimation(
    // Screen transition animation on change of selected tab.
    animateTabTransition: false,
  ),
  navBarStyle: NavBarStyle.simple, // Choose the nav bar style with this property.
);


```

Despite these settings, the tab bar continues to display a black background instead of a transparent one. Please refer to the attached screenshots for a visual representation of the issue.

**Comment by Yetispapa** [comment]
@jb3rndt I hope, I can show case my issue here. Let me know, if you have questions and thanks in advance

**Comment by jb3rndt** [comment]
Hi, you can get rid of the black background by setting `bottomScreenMargin: 0` in your `PersistentTabView`.

**Comment by Yetispapa** [comment]
@jb3rndt, nice thanks! That solved the problem
