### ISSUE TITLE
 Add vertical line in between two PersistentBottomNavBarItem using NavBarStyle.style3

### ISSUE THREAD

**Issue by pawarn** [jb3rndt/PersistentBottomNavBarV2#107]
Do we have a way to add the vertical line between two PersistentBottomNavBarItem? 

Like below.

<img width="332" alt="Screenshot 2023-09-25 at 6 13 57 PM" src="https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/32476234/90e50c53-c2fe-4880-ba3d-dfd63cbaa3c7">

Also, can we reduce the size of the PersistentBottomNavBarItem top horizontal view in purple color?

**Comment by jb3rndt** [comment]
Hi, you cant achieve that with the already included styles. But you can do everything by using a custom Navigation Bar. Just use `PersistentTabView.custom` (consider looking at the readme section for correct usage) and include whatever you want as your Navigation bar (including vertical lines and everything as you like).
