### ISSUE TITLE
How to access current tab/page once transitioned?

### ISSUE THREAD

**Issue by evanrich** [jb3rndt/PersistentBottomNavBarV2#108]
Not really a bug, and btw, AWESOME project.   I've implemented this like this:

![image](https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/518320/2d549a2f-b901-46bf-856e-2518c452804e)

But how can the "add" button in the middle (style 15) when on-pressed do something on the given page?  In this case, lets say add an item to the list?    Is there some exposed method to get the currently selected page and interact with it?

Thanks!

**Comment by jb3rndt** [comment]
Hi, I think that is possible.
You can register the `selectedTabScreenContext` callback on `PersistentTabView`. This will give you the context of the current page when switched to it, so you should save the current context in a variable somewhere. Then you can use your saved context in the onPressed method and call e.g. a provider.
I hope that helps :)
