### ISSUE TITLE
StateManagement issue

### ISSUE THREAD

**Issue by TimmyHung** [jb3rndt/PersistentBottomNavBarV2#109]
1) ~~I've set `stateManagement: false` in PersistentTabView, but the state of each tab's screen are still being preserved([VideoHere](https://streamable.com/tbr8st))~~(edit: this issue has been fixed in newest beta version).
~~And weird things happend if I have set `screenTransitionAnimation` then~~ **every** page will be rebuild when I press any bar item([VideoHere](https://streamable.com/uuupvq)). I also tested `stateManagement: true` and  set `screenTransitionAnimation` will not make every page rebuild when I press any bar item.

2) If `stateManagement: false` is not bugged, then is there's any way I can refresh the page whenever I tap the specific bottom navigation item. For instance I have a login page which will check user's states to display different widget, but after I implement PersistentBottomNavBar to replace original bottom nav bar the login page is no longer re initialize when I tap the bar item.(edit: In newest beta version,  **EVERY** pages will still initialize then dispose immediately like second video above).

**Comment by jb3rndt** [comment]
Hi, thank you for providing the videos, I can see the issues you are having. Sadly, with the code and configuration I could see in the videos, I could not reproduce the issue in your first point -> can you share a minimal code example that triggers the issue?

**Comment by TimmyHung** [comment]
Hi, thank you for the reply. I create a minimal project to reproduce this bug, also record a video to show the issue.
Currently `stateManagement: false` whenever I navigate to any page, every "loaded" page will run initState() then suddenly dispose() check the video print log.

Videos below:
https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/58425985/0cd51317-4191-4dcf-a655-728c8d06d8c6

Project libs and pubspec.yml:
[code.zip](https://github.com/jb3rndt/PersistentBottomNavBarV2/files/13254078/code.zip)

Version: `persistent_bottom_nav_bar_v2: ^5.0.0-beta.6`

**Comment by ctujare** [comment]
Has this issue been resolved???

**Comment by jb3rndt** [comment]
Sorry, yes this is fixed since version 5.0.0-beta.7.
