### ISSUE TITLE
Icon with Notification badge not implemented.

### ISSUE THREAD

**Issue by rvndsngwn** [jb3rndt/PersistentBottomNavBarV2#11]
Hey, @jb3rndt  I'm trying to add a notification badge on Persistent Bottom Nav Bar V2 but it is not compatible.

**My code**

      PersistentBottomNavBarItem(
        icon: Stack(
          alignment: Alignment.center,
          children: const [
            Icon(
              Icons.chat_rounded,
            ),
            UnreadIndicator(),
          ],
        ),
        title: ("Chat"),
      ),

**Preview** 
![IMG_1688](https://user-images.githubusercontent.com/59143934/159185418-60fb978d-90ed-4101-9899-253940f48424.jpg)

**I want like this**
![rVO5g](https://user-images.githubusercontent.com/59143934/159185508-7d3369f0-d9e2-4418-8c24-c55474a5ded6.jpeg)

**Comment by rvndsngwn** [comment]
I update my code and this issue gone. 😃

```
PersistentBottomNavBarItem(
        icon: Badge(
          animationType: BadgeAnimationType.scale,
          badgeContent: UnreadIndicator(),
          child: const Icon(
            Icons.chat_rounded,
          ),
        ),
        title: ("Chat"),
      ),
```

**Comment by jb3rndt** [comment]
Nice 👍😄

**Comment by h-unterp** [comment]
This would be a useful example for the docs
