### ISSUE TITLE
Need to Update Index of bottom navigation bar from button

### ISSUE THREAD

**Issue by itxmubi** [jb3rndt/PersistentBottomNavBarV2#111]
Hi,
I am using this package, I have a requirement, when I click Go to the second screen, I also need to update the index of the bottom navigation bar, and my selected tab will be search and the index updated from 0 to 1.

https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/63649866/41118a23-8aa0-4fe1-b073-ee12275a7019

Or if this feature is available, please refer me

**Comment by jb3rndt** [comment]
Hi, you can achieve that with the `PersistentTabController`. Just create a `PersistentTabController`, store it in a variable and pass it to `PeristentTabView`. Then, anywhere in your code, you can use your controller to invoke the `jumpToTab(1)` method. This will switch the nav bar index to 1.
