### ISSUE TITLE
Navigation bar animation does not adhere to locale: left to right and right to left (e.g. Arabic and English). 

### ISSUE THREAD

**Issue by Abdullah-RashedMW** [jb3rndt/PersistentBottomNavBarV2#114]
Navigation bar animation does not adhere to locale: left to right and right to left (e.g. Arabic and English). 
When using Easy Localization package, and switching from LTR and RTL from the package it does not apply to the bottom navigation bar tab switching animations. 

STEPS: 
set up easy localization 
set up navigation bar
change tabs with English locale (correct behavior)
change language to arabic 
switch tabs (the animation is still LTR when it should be RTL).

**Comment by abdou-tech-maker** [comment]
i have the same probleme i hope they will solve it since the package is good

**Comment by jb3rndt** [comment]
Hi, which animation exactly do you expect to change? The sliding of the pages when switching tabs?
So from what I understand: When switching from Tab 1 to Tab 2 the pages slide to the left in LTR mode. In RTL mode they should slide to the right, correct?
Same when switching from Tab 2 to Tab 1: The pages slide to the right in LTR mode. In RTL mode they should slide to the left, correct?
Feel free to open a pull request if you have a solution.

**Comment by jb3rndt** [comment]
Solved since version 5.0.0-beta.7
