### ISSUE TITLE
Screen not removing even after tab change

### ISSUE THREAD

**Issue by rishuriya** [jb3rndt/PersistentBottomNavBarV2#118]
When i am on any tab and open a page using PushWithNavBar then again click another tab after coming to to previous tab the page is still open which is creating the issue, is it possible any how that the page will close when tab change and this really fix many major issue/

**To Reproduce**
1. Click on any widget which on click PushWithNavBar and open a new stateful widget
2. In the Bottom nav bar click on any other tab,
3. Again click on the previous tab where you open the new stateful widget, you will find you didn't get the page assign to tab, you will the the page that you open

**Expected behavior**
Again on coming back to the tab, it should the page assigned to the tab, not the screen that open inside the tab.

**Comment by jb3rndt** [comment]
If you dont want every page to remember their opened pages, you can either use `pushWithoutNavBar` to be forced to close the page before switching the tabs. Or you can set `stateManagement: false`, which will cause the pages to forget their navigator state, which effectively closes all opened pages on a tab when switching to another one.
