### ISSUE TITLE
Have Floating Action Button hide on certain tabs

### ISSUE THREAD

**Issue by spectrMeltdown** [jb3rndt/PersistentBottomNavBarV2#119]
**Is your feature request related to a problem? Please describe.**
I would like to hide  the floating action button when certain tabs are selected.
I tried doing the following, but it didn't work.
```
PersistentTabView(
	...
	floatingActionButton: _controller.index == 2 ? null :  FAB(),
)
```

**Additional context**
I'm on version 5.0.0-beta.7

**Comment by jb3rndt** [comment]
Hi, you can insert the FAB on each individual page you want to have it on (it would make sense to create a separate Widget for the FAB, so it is easily reusable). Does that work for you? I dont see a reason that this should be a feature of this package, it feels like it would introduce unnessary complexity.
