### ISSUE TITLE
Restrict closing modal on android back button click.

### ISSUE THREAD

**Issue by pawarn** [jb3rndt/PersistentBottomNavBarV2#120]
Is there any way to handle the Android back button press on the modal?

I'm facing one issue when the modal is pushed using `pushDynamicScreen()` and the user clicks on the Android system back button it closes that dialog.
Is there any way to restrict the user from closing the dialog using the system back button? It works fine on iOS as there is no system back button.

` pushDynamicScreen(
        context,
        screen: HomeModalScreen(),
        withNavBar: true,
    );`
    
I'm pushing the screen using the above method.

Dialog is created like the below extends the ModalRoute and implements the override methods.
`class HomeModalScreen extends ModalRoute<void> {}`

**Comment by jb3rndt** [comment]
Normally you would do that with a `PopScope` widget that wraps your Modal content in your `buildPage` method. In this case your modal is pushed to the navigator of the current tab, so when you push the android back button, the logic of this plugin interferes with everything else and forces your modal to pop.
You have two options:
1. set `handleAndroidBackButtonPress: false` in your `PersistentTabView` (this disables the interference logic but also disables handling the android back button at all) and wrap your modal with `PopScope` and set `canPop: false`.
2. Push your Modal without the navbar -> `withNavBar: false` and wrap your modal with `PopScope` and set `canPop: false`.
