### ISSUE TITLE
How to navigate from Screen B to A using the Back Button

### ISSUE THREAD

**Issue by Tarhex** [jb3rndt/PersistentBottomNavBarV2#121]
I am having a challenge which I could not figure out in the documentation.

Let's say I tap on Settings on the Nav Bar and it opens the Settings Page. On the Settings Page, I tap on About, which opens About Page. On the About Page, I page on Contact Details, and it takes me to Contact Page. How do I go back from Contact Page to About Page and then subsequently to Settings page using the Back Button.

Thanks

**Comment by jb3rndt** [comment]
This should work by default with the `handleAndroidBackButtonPress: true` setting. What happens when you press the android back button? Nothing?

**Comment by Tarhex** [comment]
When I tap the back button, the app minimize to the background instead of
showing the dialog box.

**Comment by jb3rndt** [comment]
Ok, please make sure that `handleAndroidBackButtonPress: true` and `onWillPop: null`. If it is still not working please send me a snippet of your `PersistentTabView` creation

**Comment by Tarhex** [comment]
From the Widget tree, I just found out that the `About` page is not on top of the `Settings ` page (PersistentBottomNavBarItem). What am I doing wrong?

**Comment by Tarhex** [comment]
I had to start the app from scratch again and it worked. Thanks for the reply.
