### ISSUE TITLE
Inconsistent Icon Customization for ItemConfig in PersistentTabView

### ISSUE THREAD

**Issue by SathushChandranAL** [jb3rndt/PersistentBottomNavBarV2#122]
### Description
While using `persistent_bottom_nav_bar_v2` (version 5.0.0-beta.7), I encountered an issue where the icon customization is inconsistent between the active and inactive states in `PersistentTabView`. Specifically, the `ItemConfig` allows for a widget to be passed for the active icon, enabling the use of custom widgets such as `SvgPicture`. However, for the inactive icon, it seems only material icons can be used. This inconsistency restricts the customization capabilities and affects the UI consistency of the navigation bar.

### Expected Behavior
Both the active and inactive icons in `ItemConfig` should allow the same level of customization. Ideally, being able to pass any widget (e.g., `SvgPicture` for custom SVG icons) for both active and inactive icons would provide the necessary flexibility for app design.

### Actual Behavior
Currently, the active icon accepts a widget, allowing for custom icons (like SVGs), but the inactive icon only accepts material icons. This limits the design possibilities and makes it challenging to maintain a consistent look when the icon changes state.

### Steps to Reproduce
1. Install `persistent_bottom_nav_bar_v2` version 5.0.0-beta.7.
2. Create a `PersistentTabView` with multiple tabs.
3. Try to set a custom widget (like an SVG) as an inactive icon in `ItemConfig`.

### Suggested Solution
Allow `ItemConfig`'s inactive icon parameter to accept a widget, similar to the active icon. This change would provide developers with the flexibility to maintain a consistent and customized look for both active and inactive states.

### Additional Context
Thank you for considering this issue. The ability to fully customize icons in the navigation bar is crucial for many developers looking to provide a polished and unique user experience in their apps.

**Comment by jb3rndt** [comment]
Thank you for pointing that out, you are completely right. The fix will be included in the next beta release.

**Comment by jb3rndt** [comment]
The fix is available with version [5.0.0-beta.8](https://pub.dev/packages/persistent_bottom_nav_bar_v2/versions/5.0.0-beta.8)
