### ISSUE TITLE
context in onPressed always null.

### ISSUE THREAD

**Issue by TOMSLAUS** [jb3rndt/PersistentBottomNavBarV2#123]
When` callin onPressed in PersistentBottonNavBarItem context is always null.

Here is how the navBarItem looks.

```
PersistentBottomNavBarItem(
  icon: const FaIcon(FontAwesomeIcons.house),
  title: (t.misc.home),
  activeColorPrimary: CupertinoColors.white,
  inactiveColorPrimary: CupertinoColors.white,
  onPressed: (context){
    print(context.toString());
    if(context != null) {
    Nav.popUntil(context: context, namedRoute: TeamDashBoardPage.routeName); 
    }
  }
),
```
Sorry, for some reason code isn't formatting how its supposed to.

**Comment by jb3rndt** [comment]
Hi, I'll need a while to figure that out. Please check out the current beta version of this package (https://pub.dev/packages/persistent_bottom_nav_bar_v2/versions/5.0.0-beta.7). There is a good chance you wont have that issue there. If you have trouble migrating to the new version check out this guide: https://github.com/jb3rndt/PersistentBottomNavBarV2/blob/rework_interface/MigrationGuide.md

**Comment by jb3rndt** [comment]
Should be fixed with Version 5 :)
