### ISSUE TITLE
in 5.0.0-beta.7 , Can add  “key ” in ItemConfig

### ISSUE THREAD

**Issue by Aquarius-M** [jb3rndt/PersistentBottomNavBarV2#124]
Because guidance needs to be added to the item, a GlobalKey is required

**Comment by jb3rndt** [comment]
What do you mean with guidance?
If I understand correctly, you want the `ItemConfig` to have a `key` attribute which is the passed to the `Item` widget in all the different nav bar styles?
I would like to better understand your use case, can you elaborate a bit?

**Comment by Aquarius-M** [comment]
I used "tutorial_coach_mark" package is used for user guidance, and a key is needed in this package to obtain the component location

**Comment by Aquarius-M** [comment]
<img width="353" alt="image" src="https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/47274897/02927776-94f1-4442-b005-f546336a06bb">

like this

**Comment by jb3rndt** [comment]
Ok I understand. You can give your Icon Widget any key you want (the widget that you pass to ItemConfig). Does that work for you?
