### ISSUE TITLE
FocusScopeNode FocusScopeNode#09d05

### ISSUE THREAD

**Issue by bugrevealingbme** [jb3rndt/PersistentBottomNavBarV2#125]
I get this error when I go back to the home page with clearpage. This problem did not exist in the V1 package.

FocusScopeNode FocusScopeNode#09d05(CupertinoTabScaffold Tab 0)(context: FocusScope, focusedChildren: [FocusScopeNode#adf25(_ModalScopeState<dynamic> Focus Scope)]) must be a child of FocusScopeNode#5a1d9(_ModalScopeState<dynamic> Focus Scope)(context: FocusScope) to set it as first focus.

The relevant error-causing widget was:
    PersistentTabView-[<'PersistentTabView'>] PersistentTabView:file:///Users/bmerdogan/Metareverse/date_planner/lib/views/main_view.dart:54:18

**Comment by jb3rndt** [comment]
Thank you for reporting. Please tell me the version of the package you are using. And I dont fully understand what I need to do to trigger this error. Can you elaborate what you mean with "clearpage"? A code snippet might me helpful for me to understand your issue as well :)

**Comment by bugrevealingbme** [comment]
I'm using: persistent_bottom_nav_bar_v2: ^5.0.0-beta.8

When I go to my home page with the pushReplacementNamed function, I get this error and the application seems to crash.

**Comment by bugrevealingbme** [comment]
More:

FocusScopeNode FocusScopeNode#ad3cc(CupertinoTabScaffold Tab 0)(context: FocusScope, focusedChildren: [FocusScopeNode#7fa06(_ModalScopeState<dynamic> Focus Scope)]) must be a child of FocusScopeNode#e9f28(_ModalScopeState<dynamic> Focus Scope [PRIMARY FOCUS])(context: FocusScope, PRIMARY FOCUS) to set it as first focus.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 1347 pos 12: 'scope.ancestors.contains(this)'

(elided 2 frames from class _AssertionError)

The element being rebuilt at the time was index 16 of 1494: _TabSwitchingView
    dirty
    dependencies: [_FocusInheritedScope]
    state: _TabSwitchingViewState#311d4(tickers: tracking 1 ticker)

The relevant error-causing widget was:
    PersistentTabView 
════════ Exception caught by scheduler library ═════════════════════════════════
buildScope missed some dirty elements.
The list of dirty elements at the end of the buildScope call was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Duplicate GlobalKey detected in widget tree.
════════════════════════════════════════════════════════════════════════════════

**Comment by bugrevealingbme** [comment]
I was making the controls global and using them. The problem was when I put the same controls back in the same widget. I solved the problem by modifying my code a bit.

**Comment by hardyio** [comment]
> I was making the controls global and using them. The problem was when I put the same controls back in the same widget. I solved the problem by modifying my code a bit.

How was it solved? I also encountered the same problem

**Comment by jb3rndt** [comment]
Which version are you using? If it is not the latest 5.4.0 then upgrade to that please and try again. If that does not solve it, could you share code that reproduces the problem? :)
