### ISSUE TITLE
SVG image instead of Icon

### ISSUE THREAD

**Issue by ctujare** [jb3rndt/PersistentBottomNavBarV2#126]
Current Output when SVG image is used instead of an Icon

![Screenshot 2024-02-12 155116](https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/19292827/64e43efb-4f70-4178-bdd6-8509ecb05add)

Is there a way I can use the SVG image instead of the icon

Currently the plus is an icon using Icon() and the other 3 are SvgPicture.asset()

**Comment by lcardozoaplauze** [comment]
Try this:
```dart
PersistentBottomNavBarItem(
  icon: Container(
    alignment: Alignment.center,
    child: SvgPicture.asset(
      "icon.svg",
      width: 20,
      height: 20,
      colorFilter: ColorFilter.mode(
        Colors.red,
        BlendMode.srcIn,
      )
    )
  ),
  inactiveIcon: Container(
    alignment: Alignment.center,
    child: SvgPicture.asset(
      "icon.svg",
      width: 20,
      height: 20,
      colorFilter: ColorFilter.mode(
        Colors.blueGrey,
        BlendMode.srcIn,
      )
    )
  ),
  // ...
);
```

**Comment by jb3rndt** [comment]
Thank you for reporting this issue. From what I can seee you are using version 5 of the package with the prebuilt style 1? I found the error and it will be fixed with the next version of the beta. Thanks @lcardozoaplauze for posting a fix.

**Comment by jb3rndt** [comment]
Resolved with version 5.0.0-beta.9

**Comment by ctujare** [comment]
This is perfect ... Thank you sooo much

**Comment by ctujare** [comment]
> Try this:
> ```dart
> PersistentBottomNavBarItem(
>   icon: Container(
>     alignment: Alignment.center,
>     child: SvgPicture.asset(
>       "icon.svg",
>       width: 20,
>       height: 20,
>       colorFilter: ColorFilter.mode(
>         Colors.red,
>         BlendMode.srcIn,
>       )
>     )
>   ),
>   inactiveIcon: Container(
>     alignment: Alignment.center,
>     child: SvgPicture.asset(
>       "icon.svg",
>       width: 20,
>       height: 20,
>       colorFilter: ColorFilter.mode(
>         Colors.blueGrey,
>         BlendMode.srcIn,
>       )
>     )
>   ),
>   // ...
> );
> ```

This worked like a charm ... Thank you
