### ISSUE TITLE
How to change icon size?

### ISSUE THREAD

**Issue by mikegitdev** [jb3rndt/PersistentBottomNavBarV2#13]
How Can I change Icon size ?
I am using  `NavBarStyle.style16, `
![image](https://user-images.githubusercontent.com/37968013/160208671-2a41434e-62e5-4e4b-a16d-b621a7a31370.png)

**Comment by jb3rndt** [comment]
You can set the icon size for each icon individually through the `PersistentBottomNavBarItem` of the item you want the iconsize to change.
Example:
```dart
PersistentBottomNavBarItem(
  iconSize: 42.0,
)
```
