### ISSUE TITLE
Missing padding/content at the bottom of the "page" is behind the nav bar in 5

### ISSUE THREAD

**Issue by BarryCarlyon** [jb3rndt/PersistentBottomNavBarV2#130]
Package Version (from pubspec.yaml): `persistent_bottom_nav_bar_v2: ^5.0.0`

**Bug Description**

In 4 this plugin auto added "padding" to to the bottom so content at the bottom of the page could be scrolled to.
Or prevented content appear behind the nav bar.

Under 5 that doesn't seem to be the case, having only swapped from 4 to 5 my "tall pages" I cannot scroll to the end of the content on my pages as the page bottom/end of content is behind the nav bar.

Where as in 4 it was correctly aligned

**Expected behavior**

I don't need to add padding myself to the scaffold/content (well in 5 scaffold is replaced by `PersistentTabView` but you get what I mean I think?

**Comment by jb3rndt** [comment]
Hi, thank you for reporting. If I understand right, you just need to add `navBarOverlap: NavBarOverlap.none()` as an argument to your `PersistentTabView`. Does that solve your issue?

**Comment by BarryCarlyon** [comment]
I will test that as soon as possible and let you know (currently sat in sfo airport about to get on a plane)
But that does sound pluasible. (And if it solves the issue, might warrant to be added to the migration guide)

**Comment by BarryCarlyon** [comment]
Yes this fixes the issue I was having!
