### ISSUE TITLE
Is there any chance to keep the navibar still when keyboard collapses?

### ISSUE THREAD

**Issue by liujian-930212** [jb3rndt/PersistentBottomNavBarV2#132]
As the example code provided in this repo, keyboard collapses  when the "done" button is hit. And I noticed that the navibar has a brief animation of rising up.

So I wonder if there is a way to keep the Navibar still.

Thank you

**Comment by jb3rndt** [comment]
Hi, thank you for pointing this out. I found the issue and will include it in the next release :)

**Comment by jb3rndt** [comment]
This is fixed with version [5.1.0](https://pub.dev/packages/persistent_bottom_nav_bar_v2)
