### ISSUE TITLE
Slide / Reveal Transition

### ISSUE THREAD

**Issue by jtkeyva** [jb3rndt/PersistentBottomNavBarV2#140]
**Is your feature request related to a problem? Please describe.**
There is only ability to Slideright. Would be nice if you could reveal the next page beneath the current one. kinda like a deck of cards

**Describe the solution you'd like**
Ability to revealLeft revealRight revealUp revealDown etc  like a deck of cards

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by jb3rndt** [comment]
Currently, there are no plans of supporting this out of the box. In my opinion this would require a more general approach that allows all kinds of gesture interactions and revealing animations to be implemented. Maintaining all possibilities inside the package would probably explode its complexity and weight. Feel free to come up with ideas or open a pull request.

If you dont rely on the gesture, take a look at `PersistentTabView.animatedTabBuilder`. This builder function allows you to customize the transition animation when switching tabs.

**Comment by jtkeyva** [comment]
Got it thank you. Perhaps this can help? https://pub.dev/packages/go_transitions

Also, off topic, but is it possible to slide up the navebar like a drawer? Perhaps with a gesture to pull it up and reveal more content below it?

**Comment by jb3rndt** [comment]
I think it should be possible, but never tried it. You can create a custom navbar that implements this behavior and pass it to the `navBarBuilder` argument. Maybe make your navbar stateful and put a gesturedetector around it to update its size when it is dragged
