### ISSUE TITLE
pushNamed not working

### ISSUE THREAD

**Issue by carlosriveroib** [jb3rndt/PersistentBottomNavBarV2#16]
In the example, if I change the onPressed method in the MainScreen widget to use pushNamed, Navigator doesn't work.

```dart
onPressed: () {
  pushNewScreenWithRouteSettings(
    context,
    settings: RouteSettings(name: '/home'),
    screen: MainScreen2(),
    pageTransitionAnimation:
    PageTransitionAnimation.scaleRotate,
  );
},
```

to this

```dart
onPressed: () {
  Navigator.of(context).pushNamed('/first');
},
```

but this works

```dart
onPressed: () {
  Navigator.of(context).push(
    MaterialPageRoute(builder: (_) => MainScreen2())
  );
},
```

Am I doing something bad?
Why this is not working?

Thank you very much

**Comment by jb3rndt** [comment]
In the example, the first `PersistentBottomNavBarItem` in the `_navBarsItems` function has no `routeAndNavigatorSettings` like the other items have. So it should work if you push the button on another tab, or if you add the following to the first item as well:
```
routeAndNavigatorSettings: RouteAndNavigatorSettings(
  initialRoute: '/',
  routes: {
    '/first': (context) => MainScreen2(),
    '/second': (context) => MainScreen3(),
  },
),
```
I hope it works for you then :)

**Comment by jb3rndt** [comment]
For a custom PersistentBottomNavBar, you have to specify your routes in `PersistentBottomNavBar.custom` like this:
```dart
PersistentBottomNavBar.custom(
  ...
  routeAndNavigatorSettings: CustomWidgetRouteAndNavigatorSettings(
    initialRoute: '/',
    routes: {
      '/first': (context) => MainScreen2(),
      '/second': (context) => MainScreen3(),
    },
  ),
...
)
```
The route settings will apply to every tab in this case. For the custom navbar, the route settings in the `PersistentBottomNavBarItem` are ignored.

**Comment by carlosriveroib** [comment]
Nice. I really appreciate your help. Thank you
