### ISSUE TITLE
[Bug]: the navigation bar is showing on top of the keyboard 

### ISSUE THREAD

**Issue by abdou-tech-maker** [jb3rndt/PersistentBottomNavBarV2#164]
### Version

5.2.3

### Flutter Doctor Output

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-x64, locale fr)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
mac@MacBook-Pro-de-Mac sourcing %
```

### What platforms are you seeing the problem on?

Android, iOS

### What happened?

when i have migrated to the latest version i found that hideNavBarWhenKeyboardIsOpen field has been removed and now i could not find any field or way to hide the navigation bar .

am i missing something or there is a way to hide it 

### Code to reproduce the problem

```dart
just create a navigation bar using this package and try to input something in a textfield
```

### Screenshots

![Simulator Screenshot - iPhone 15 Pro Max - 2024-05-21 at 18 31 36](https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/60049661/ee300b39-6728-4352-a0e3-485a24895569)

**Comment by abdou-tech-maker** [comment]
@jb3rndt  could you please provide an answer ?

**Comment by jb3rndt** [comment]
Hi, have you read the [Migration guide](https://github.com/jb3rndt/PersistentBottomNavBarV2/blob/master/MigrationGuide.md)? Especially, make sure that there is not a single `Scaffold` above your `PersistentTabView` widget.

**Comment by abdou-tech-maker** [comment]
@jb3rndt  thank you a

**Comment by abdou-tech-maker** [comment]
@jb3rndt  thank you i must have missed that when reading the migration guide ( keep up the good work)

**Comment by willxie** [comment]
@jb3rndt Is there a way to use PersistentBottomNavBarV2 inside a Scaffold? For my application, I have containers on the left, right, and upper parts of the screen. PersistentBottomNavBarV2 and the tabs are located on the center. I can't find a way to not wrap PersistentBottomNavBarV2 container inside a Scaffold and seeing the same keyboard issue as the result.

**Comment by jb3rndt** [comment]
I'm not entirely sure that I understand how you need a scaffold for that 😅  Cant you wrap the `PersistentBottomNavBarV2` in a custom widget that handles your left, right and upper containers? I guess you're building a desktop app?
