### ISSUE TITLE
Custom Item Width

### ISSUE THREAD

**Issue by enes-kal** [jb3rndt/PersistentBottomNavBarV2#172]
I have face problem with long text. The button width is fixed in style 2 this couse an sytex error I fixed by add a new variable width to ItemConfig and use at Style2BottomNavBar > _buildItem >AnimatedContainer

"width: isSelected ? deviceWidth * item.width : deviceWidth * 0.12, "

like this this is must be fixed

thank you.

<img width="475" alt="Ekran Resmi 2024-06-22 09 24 04" src="https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/63354478/6f6df794-f566-4657-98c7-84a753692a29">

Long Not Fit Here
<img width="328" alt="Ekran Resmi 2024-06-22 09 23 22" src="https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/63354478/8381c13f-74b9-4c7f-bdbd-f6f73856ffa5">

<img width="561" alt="Ekran Resmi 2024-06-22 09 23 52" src="https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/63354478/0bfc6157-16e8-4653-aa62-fb6fbc44a9e7">

**Comment by jb3rndt** [comment]
You are free to just copy the style you want into a custom file, do some adjustments, and use the new style like the old one.

**Comment by enes-kal** [comment]
I cant set a custom width to items. there is no variable like width in ItemConfic class this is the issue
