### ISSUE TITLE
Is it possible that stateManagement can affect Google Maps Flutter?

### ISSUE THREAD

**Issue by kawi15** [jb3rndt/PersistentBottomNavBarV2#175]
I am wondering, following to this: [https://github.com/flutter/flutter/issues/150975](url) if this plugin and his stateManagement can affect google maps?

I have in one of my tab implemented google maps and it is working smooth and fine, but when I came back to app which was some time in background, it came back to first index and then when I opened tab with maps, they started lagging.

I wonder if it's somehow possible?

I have this code in my ```onTabChanged``` function, I don't know at all, maybe it can generate trouble?

```
if (Navigator.canPop(selectedTabContext!)) {
            Navigator.of(selectedTabContext!).popUntil((route) => route.isFirst);
}
```

**Comment by jb3rndt** [comment]
Hm, no I dont know of any effects on packages like google maps and have not seen similar problems.
