### ISSUE TITLE
 How to apply transparency in nav?

### ISSUE THREAD

**Issue by AllanCoinaski** [jb3rndt/PersistentBottomNavBarV2#181]
How to apply transparency in nav?

I have a background with an image, and I would like this image to be visible behind the nav. Is it possible?

I tried to do it the way below. Did I do something wrong?

     PersistentTabView (
        navBarBuilder: (navBarConfig) => Style15BottomNavBar(
        navBarConfig: navBarConfig,
        navBarDecoration: NavBarDecoration(
          borderRadius: BorderRadius.zero,
          color: Colors.transparent,
        ),
      ),
      navBarOverlap: NavBarOverlap.full(),
      controller: _controller,

      tabs: [
        PersistentTabConfig(
            screen: ProfileScreen(),
            item: ItemConfig(
              activeColorSecondary: Colors.white,
              title: "Perfil",
              textStyle: FontsModel.defaultFont.copyWith(fontSize: 12),
              icon: SvgPicture.asset(
                ("assets/icons/person.svg"),
                height: 25,
                color: Colors.white,
              ),
            )),
        PersistentTabConfig(
            screen: HomeScreen(),
            item: ItemConfig(
              activeColorSecondary: Colors.white,
              title: "Home",
              textStyle: FontsModel.defaultFont.copyWith(
                fontSize: 11,
              ),
              icon: SvgPicture.asset(
                ("assets/icons/home.svg"),
                height: 25,
                color: ColorsModel.background,
              ),
            )),
        PersistentTabConfig(
            screen: GalleryScreen(),
            item: ItemConfig(
              activeColorSecondary: Colors.white,
              title: "Pontos",
              textStyle: FontsModel.defaultFont.copyWith(fontSize: 12),
              icon: SvgPicture.asset(
                ("assets/icons/gallery.svg"),
                height: 25,
                color: Colors.white,
              ),
            )),
      ],
      screenTransitionAnimation: ScreenTransitionAnimation(
        curve: Curves.ease,
        duration: Duration(milliseconds: 200),
      ),
    );

Output:
![Captura de Tela 2024-09-26 às 14 05 47](https://github.com/user-attachments/assets/5516fb1b-d17c-47dc-92e7-d210c1d44688)

**Comment by jb3rndt** [comment]
Thank you, there was an error in the package. I just fixed it and everything should work with v5.3.1
