### ISSUE TITLE
Random string printed when switching tabs

### ISSUE THREAD

**Issue by JustJaw** [jb3rndt/PersistentBottomNavBarV2#2]
When clicking on a nav bar item, this string will be printed out "Blassssfhlksajkdös". Is it possible to remove this?

**Comment by gumdum** [comment]
ditto..and the FAB button is keeping state for me. I can't get it to refresh properly

**Comment by jb3rndt** [comment]
> When clicking on a nav bar item, this string will be printed out "Blassssfhlksajkdös". Is it possible to remove this?

Yep, sorry its away now

**Comment by jb3rndt** [comment]
> ditto..and the FAB button is keeping state for me. I can't get it to refresh properly

Can you give me a code example to recreate the issue?
