### ISSUE TITLE
Badge with existing style!

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [jb3rndt/PersistentBottomNavBarV2#21]
https://github.com/BilalShahid13/PersistentBottomNavBar/issues/281

**Comment by jb3rndt** [comment]
Yeah that is an interesting request. It might take some time to support that because it needs some core rework of the package. But I'm already trying something out, so I'll keep you up to date

**Comment by vytautas-pranskunas-** [comment]
```
 PersistentBottomNavBarItem(
        icon: Badge(
          badgeContent: Text('3'),
          child: Icon(Icons.settings),
        ),
        title: ("Settings"),
        activeColorPrimary: Colors.blue,
        inactiveColorPrimary: Colors.grey,
      ),
```

**Comment by jb3rndt** [comment]
Happy that you were able to solve that, I probably had something different in mind
