### ISSUE TITLE
Elevation of navbar

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [jb3rndt/PersistentBottomNavBarV2#22]
Is there a way to add elevation so the shadow is visible on the top?

**Comment by jb3rndt** [comment]
It is possible if you build your own navBar using customWidget. But for the predefined styles you can pass a list of custom baxShadows to the `NavBarDecoration`. Using elevation is not supported yet but I can look into it

**Comment by vytautas-pranskunas-** [comment]
@jb3rndt could you drop here small example becuase i cannot see property where I can pass ```NavBarDecoration```

**Comment by vytautas-pranskunas-** [comment]
i found it sry:

```
decoration: NavBarDecoration(
        borderRadius: BorderRadius.circular(10.0),
        colorBehindNavBar: Colors.white,
        boxShadow: <BoxShadow>[
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 5,
          ),
        ],
      ),
```
