### ISSUE TITLE
Make nested navigation compatible PersistentBottomNavBar.

### ISSUE THREAD

**Issue by rvndsngwn** [jb3rndt/PersistentBottomNavBarV2#24]
Hey @jb3rndt 

**Feature request:-**
 [PersistentBottomNavBarV2](https://github.com/jb3rndt/PersistentBottomNavBarV2) compatibility with nested navigation.

Sometimes you want to choose a page based on a route as well as the state of that screen, e.g. the currently selected tab. In that case, you want to choose not just the screen from a route but also the widgets nested inside the screen. That's called "nested navigation". The key differentiator for "nested" navigation is that there's no transition on the part of the page that stays the same, e.g. the app bar stays the same as you navigate to different tabs on this TabBarView:

![](https://raw.githubusercontent.com/csells/go_router/HEAD/docs/images/nested-nav.gif)

Of course, you can easily do this using the TabBarView widget, but what makes this nested "navigation" is that the location changes, i.e. notice the address bar as the user transitions from tab to tab. This makes it easy for the user to capture a [dynamic link](https://gorouter.dev/parameters/#dynamic-linking) for any object in the app, enabling [deep linking](https://gorouter.dev/declarative-routing#deep-linking).

**Examples:-**
- https://gorouter.dev/nested-navigation
- https://pub.dev/packages/auto_route#nested-navigation 

**Thanks for maintaining a great package** 🫡

**Comment by jb3rndt** [comment]
I finally managed to create a first beta for using the flutter Router API with go_router. Check out the newest beta [5.0.0-beta.6](https://pub.dev/packages/persistent_bottom_nav_bar_v2/versions/5.0.0-beta.6) and the corresponding [readme section](https://pub.dev/packages/persistent_bottom_nav_bar_v2/versions/5.0.0-beta.6#router-api). Let me know if everything works as expected and if something is missing.
