### ISSUE TITLE
Content of page disappearing and FullScreen for Videos

### ISSUE THREAD

**Issue by saiyajindont** [jb3rndt/PersistentBottomNavBarV2#27]
When i'm changing of page through NavBar sometimes the content of the page disappears, there is any solution?
And when i'm on fullscreen mode i want to hide the navBar, how can i do that?

**Comment by saiyajindont** [comment]
How to change the route when you click on a PersistentBottom?

**Comment by jb3rndt** [comment]
> When i'm changing of page through NavBar sometimes the content of the page disappears, there is any solution?

On what particular occasions does that happen? Is there some behavioral pattern you can recognize? Maybe it is related to https://github.com/jb3rndt/PersistentBottomNavBarV2/issues/3 which should be fixed though...

> And when i'm on fullscreen mode i want to hide the navBar, how can i do that?

You can push a new screen without the navbar by using
```dart
pushNewScreen(
    context,
    screen: MainScreen(),
    withNavBar: false,
);
```
or alternatively
```dart
Navigator.of(context, rootNavigator: true).push(...);
```

> How to change the route when you click on a PersistentBottom?

Can you please explain that a bit more?

**Comment by saiyajindont** [comment]
I solved the problem of the page disappearing, now i have another problem: When i use your tip of pushNewScreen there's no navBar, how can i solve this?

**Comment by saiyajindont** [comment]
The context is that i'm using an iconButton on appBar and onpressed i use navigator, to push to a new page. When i go to this new page there's no navBar

**Comment by jb3rndt** [comment]
I assume you did set `withNavBar: true` in the call of `pushNewScreen`? If not, try if that works in your case.
Otherwise, it could be that the `context` you pass into `pushNewScreen` is not the context of the currently active page. So if the first solution did not help, you can check if the `context` is correct.
