### ISSUE TITLE
Black screen appears when fastly switching tab

### ISSUE THREAD

**Issue by FelderCamille** [jb3rndt/PersistentBottomNavBarV2#3]
Hi,

The problem is already explained in the title. Here is a link of the same issue from the old project : https://github.com/BilalShahid13/PersistentBottomNavBar/issues/164

Is it possible to fix it ?
Thank you 😊

**Comment by jb3rndt** [comment]
Looking into it

**Comment by jb3rndt** [comment]
It should now be fixed since version 4.1.6
