### ISSUE TITLE
PersistantNav.Custom background issue

### ISSUE THREAD

**Issue by MohammadRijwan** [jb3rndt/PersistentBottomNavBarV2#32]
How to remove this color I tried colors.Transparent but It give black. 
Please provide information about this, how can I change this. 
![Screenshot_20220602-172502](https://user-images.githubusercontent.com/980834/171623985-441ea38a-8203-4658-b720-1688b195d364.png)

**Comment by jb3rndt** [comment]
Where did you set `Colors.transparent`?

It should work with `backgroundColor` in `PersistentNavBar.custom`:
```dart
PersistentNavBar.custom(
  ...
  backgroundColor: Colors.purple,
  ...
)
```
If that doesnt work, you might have to check your CustomNavBar widget if there is some Container or so that draws a background.

**Comment by MohammadRijwan** [comment]
> Where did you set `Colors.transparent`?
> 
> It should work with `backgroundColor` in `PersistentNavBar.custom`:
> 
> ```dart
> PersistentNavBar.custom(
>   ...
>   backgroundColor: Colors.purple,
>   ...
> )
> ```
> 
> If that doesnt work, you might have to check your CustomNavBar widget if there is some Container or so that draws a background.

no its not working but I fixed it by using Custom Painter
