### ISSUE TITLE
Scroll to Top doesn't work on iOS

### ISSUE THREAD

**Issue by mark8044** [jb3rndt/PersistentBottomNavBarV2#34]
On iOS apps, tapping the top status bar should scroll to the top, which doesn't work here

**Comment by pavittarsingh315** [comment]
I'm pretty sure you have to implement this on your own anyways in Flutter. I use a ScrollController and animate to 0 when I want to achieve this functionality.

**Comment by jb3rndt** [comment]
Oh sorry for not responding. Do you @mark8044 think this is an issue related to this package? As @pavittarsingh315 said, It is a functionality that has to be specifically implemented for each use case. So it might neither fit in this package, nor it is solvable uniformly. What do you think?

**Comment by ne-ray** [comment]
assign BilalShahid13/PersistentBottomNavBar/issues/178

**Comment by ne-ray** [comment]
> I'm pretty sure you have to implement this on your own anyways in Flutter. I use a ScrollController and animate to 0 when I want to achieve this functionality.

Can you give example please?

**Comment by ne-ray** [comment]
assign BilalShahid13/PersistentBottomNavBar/issues/293
