### ISSUE TITLE
debugging text is print upon click

### ISSUE THREAD

**Issue by mohadel92** [jb3rndt/PersistentBottomNavBarV2#4]
When i click on any tab to navigate
a text `Blassssfhlksajkdös ` is always print 
i think it is caused via package the original one didn't have this bug

**Comment by Stratovarius93** [comment]
I have same print. Any solution?

**Comment by alaxcc** [comment]
hey, bro, you can fork this repository, and modify dependency in pubspec.yaml like this:


persistent_bottom_nav_bar_v2:
    git: git@github.com:your github Id/PersistentBottomNavBarV2.git

and then run 
flutter clean && flutter pub get

that can solve it.

**Comment by jb3rndt** [comment]
Yeah sorry, it should not happen anymore in since version 4.1.2

**Comment by jb3rndt** [comment]
> hey, bro, you can fork this repository, and modify dependency in pubspec.yaml like this:
> 
> `persistent_bottom_nav_bar_v2:` 　　`git: git@github.com:your github Id/PersistentBottomNavBarV2.git`
> 
> and then run `flutter clean && flutter pub get`
> 
> that can solve it.

Nice workaround though ^^
