### ISSUE TITLE
How to extend the body's of screens past the NavBar?

### ISSUE THREAD

**Issue by pavittarsingh315** [jb3rndt/PersistentBottomNavBarV2#43]
So basically I am using this package for the first time and it really is amazing. So much is included out of the box. 

I believe this is a missing feature and not a bug. Essentially, when I declare `PersistentTabView.custom(...)`, I'd like the screens that I defined in the `PersistentTabView` to extend past the body making the content of the current screen extend past the navbar.

Is this already possible and I'm just not seeing it or is this a missing feature?

Thank you!

**Comment by jb3rndt** [comment]
It's already possible, you can just set `bottomScreenMargin` to `0.0` like this:
```dart
PersistentTabView.custom(
  ...
  bottomScreenMargin: 0.0,
  ...
)
```

I hope it solves your case ^^

**Comment by pavittarsingh315** [comment]
Yes it does. Thank you!
