### ISSUE TITLE
How to add a screen to another tab by pressing a button in the screen?

### ISSUE THREAD

**Issue by fushihara** [jb3rndt/PersistentBottomNavBarV2#45]
![Persistent Behavior](https://github.com/jb3rndt/PersistentBottomNavBarV2/raw/master/gifs/persistent.gif)
In the sample app as shown in the video, how do I add a screen to the stack by pressing the button in the center of the screen and moving from the Home tab to the magnifying glass tab on the right side?

Switching tabs from within the screen could be done using PersistentTabController.

How do I add any screen to the screen stack of another tab?

**Comment by jb3rndt** [comment]
Yes you can use `PersistentTabController` to switch the tab and then you have to set a navigator key for each tab and use the key of the tab you want to push the page on. In this example is switches to tab 2 and pushes a screen there:
```
tabController.jumpToTab(1);
SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
  secondScreenNavigator.currentState.push(MaterialPageRoute(
      builder: (BuildContext context) => MainScreen2()));
});
```

**Comment by fushihara** [comment]
Thank you!
It was very helpful.


I'll leave a snippet of the code for future reference.

```dart
final GlobalKey<NavigatorState> _navigatorKey0 = GlobalKey<NavigatorState>();
PersistentBottomNavBarItem(
                routeAndNavigatorSettings: RouteAndNavigatorSettings(
                    navigatorKey: _navigatorKey0)),
```
