### ISSUE TITLE
'TextStyle' is not a subtype of type 'Color?' in type cast

### ISSUE THREAD

**Issue by Artem-Pronenko** [jb3rndt/PersistentBottomNavBarV2#47]
In the PersistentBottomNavBarItem class, the textStyle property expects the type TextStyle? but due to the use of as Color in the class implementation, we get this error. (NavBarStyle.style3)

Or am I doing something wrong?

```
      #0      BottomNavStyle3._buildItem (package:persistent_bottom_nav_bar_v2/nav-bar-styles/style-3-bottom-nav-bar.widget.dart:65:72)
      #1      BottomNavStyle3.build.<anonymous closure> (package:persistent_bottom_nav_bar_v2/nav-bar-styles/style-3-bottom-nav-bar.widget.dart:164:32)
      #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
      #3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
      #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
      #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
      #6      new List.of (dart:core-patch/array_patch.dart:51:28)
      #7      ListIterable.toList (dart:_internal/iterable.dart:213:44)
      #8      BottomNavStyle3.build (package:persistent_bottom_nav_bar_v2/nav-bar-styles/style-3-bottom-nav-bar.widget.dart:171:20)
```

**Comment by chiptech-andrew** [comment]
This is also an issue for us, and is an issue that was present in the original package, PersistentBottomNavBar https://github.com/BilalShahid13/PersistentBottomNavBar/issues/195. 

I'm new to Flutter, so for now I've removed the piece of our code that sets the textStyle property in PersistentBottomNavBarItem.
Original code that isn't working:
```
return PersistentBottomNavBarItem(
      icon: Icon(
        icon,
        size: iconSize ?? 33.0,
      ),
      title: title,
      textStyle: const TextStyle(
        fontSize: 10.0,
      ),
      activeColorPrimary: Theme.of(context).colorScheme.secondary,
      inactiveColorPrimary: Theme.of(context).iconTheme.color,
    );
```

Removed textStyle:
```
return PersistentBottomNavBarItem(
      icon: Icon(
        icon,
        size: iconSize ?? 33.0,
      ),
      title: title,     
      activeColorPrimary: Theme.of(context).colorScheme.secondary,
      inactiveColorPrimary: Theme.of(context).iconTheme.color,
    );
```

Supposedly this is only an issue impacting NavBarStyle.style3 (which is what we are using), so changing styles would probably fix this too.

**Comment by jb3rndt** [comment]
Ok thank you, this issue should be fixed with https://github.com/jb3rndt/PersistentBottomNavBarV2/releases/tag/v4.2.4

**Comment by whitecodel** [comment]
## Style 3 Issue fixed (For `persistent_bottom_nav_bar` users)

If you are using **`persistent_bottom_nav_bar`** (not **`persistent_bottom_nav_bar_v2`**), there is currently an issue with **Style 3**. I've created a pull request to the `master` branch with a fix.

If you don’t want to wait for the next release or upgrade to version 2, you can use the following workaround without changing your existing code:

```yaml
persistent_bottom_nav_bar:
  git:
    url: https://github.com/whitecodel/PersistentBottomNavBar.git
    ref: fix/style3-textstyle-cast-error
