### ISSUE TITLE
Not back arrow when push page

### ISSUE THREAD

**Issue by nowjordanhappy** [jb3rndt/PersistentBottomNavBarV2#48]
i'm testing the example and event if I push a new page, the back arrow is not showing

**Comment by jb3rndt** [comment]
If you want to have the back arrow on the pages that you push with the navbar, you need to give every single screen a scaffold with an AppBar. Then you should also remove the scaffold around your `PersistentTabView` if there is one.

So to make that work in the example, you need to remove the scaffold in the build method of the `ProvidedStyleExample` and add an AppBar to `MainScreen` and `MainScreen2` for example.

Does that solve your issue?
