### ISSUE TITLE
Using Go Router with PersistentBottomNavBar

### ISSUE THREAD

**Issue by LennartMart** [jb3rndt/PersistentBottomNavBarV2#52]
I'm building a new app in Flutter with Go_Router and PersistentBottomNavBar (Since all new recipes point to Go_Router as the go-to navigation solution). Is there an option to integrate Go_Router with PersistentBottomNavBar?
If I do something like `                    pushNewScreenWithRouteSettings(
                      context,
                      screen: ProductsListScreen(),
                      settings: RouteSettings(name: "/products"),
                    );`, 
the page isn't pushed to the stack of Go_Router.

**Comment by LennartMart** [comment]
A bit too quick while creating this issue :) Found a solution in #48 : Create AppBar & Drawer in separate widgets, and use them in every screen (instead of applying in on the PersistentTabView).

**Comment by LennartMart** [comment]
For other people that want to user this navbar with Go_Router:

1. Remove AppBar & Drawer from the Scaffold with the navbar
2. Add them to every separate screen
3. Using Go_Router inside the tabs of the navbar is impossible. Just go with pushNamedScreen on these occasions

If you're using EndDrawer, you'll need to add this in your AppBar:
`      leading:
          (ModalRoute.of(context)?.canPop ?? false) ? const BackButton() : null,`

**Comment by jb3rndt** [comment]
I'll look at it, but it might take some time as I never used Go_Router. There is actually another issue related to that already #24. I will reopen the issue to keep track of it.

**Comment by DynxstyGIT** [comment]
Any news on this?

**Comment by jb3rndt** [comment]
Not really, I had no time yet to take a deep look into it. Maybe after the beta is released

**Comment by DynxstyGIT** [comment]
> Not really, I had no time yet to take a deep look into it. Maybe after the beta is released

Alrighty, thanks for the quick reply. Since i'm in the middle of implementing the go_router into my project, it's pretty crucial for me that this works. Haven't tried if those issues actually affect me, but if they do, i'll maybe just investigate that myself and do a quick pr

**Comment by jb3rndt** [comment]
If you are in the topic already anyway, a PR would be a huge help, so dont hesitate :)

**Comment by jb3rndt** [comment]
The newest beta contains support for go_router. See this issue for more information: https://github.com/jb3rndt/PersistentBottomNavBarV2/issues/24.
Closing this as a duplicate.
