### ISSUE TITLE
Prevent tab change with the back key

### ISSUE THREAD

**Issue by DomenicoParisiWeb** [jb3rndt/PersistentBottomNavBarV2#53]
Hello everybody,

I need help.
The back key works fine, but when I get to the "base" of the current tab, if I click the back key again it takes me back to the first tab, can I prevent this last behavior?

Many thanks in advance.

**Comment by jb3rndt** [comment]
Do you mean the android back button? You can set `handleAndroidBackButtonPress: true` on your `PersistentTabView` which should hopefully fix it?

**Comment by DomenicoParisiWeb** [comment]
It is already `handleAndroidBackButtonPress: true`.
It works fine, but when there are no more pages to go back, if I press it it takes me to the first tab.
This last behavior I would like to prevent...

**Comment by DomenicoParisiWeb** [comment]
In summary "handleAndroidBackButtonPress" works well, but the problem remains that it switches to the first tab if there are no previous pages in that tab.

I am implementing "onWillPop", how can I check to return false when there are no "previous pages"?

**Comment by jb3rndt** [comment]
I cant find any errors on your side, so I will try to create a new parameter that allows specifying if you want to switch to the first tab or not.

**Comment by jb3rndt** [comment]
Oh wait I actually found a way to do what you want. I guess the reason why your navigator reports false histories is the buildcontext you are using. If you always take the context of the currently selected tab, you can use that in the `onWillPop` method, to pop any additional screens on that tab while doing nothing if there are no additional screens. To make that work, `handleAndroidBackButtonPress` has to be `false`.
Here is an example:

```dart
class ProvidedStyleExample extends StatefulWidget {
  ProvidedStyleExample({Key key}) : super(key: key);

  @override
  _ProvidedStyleExampleState createState() => _ProvidedStyleExampleState();
}

class _ProvidedStyleExampleState extends State<ProvidedStyleExample> {
  BuildContext currentContext;

  List<Widget> _buildScreens() {
    return [
      MainScreen(
        onScreenHideButtonPressed: () {},
      ),
      MainScreen(
        onScreenHideButtonPressed: () {},
      ),
    ];
  }

  List<PersistentBottomNavBarItem> _navBarsItems() {
    return [
      PersistentBottomNavBarItem(
        icon: Icon(Icons.home),
        title: "Home",
        activeColorPrimary: Colors.blue,
        inactiveColorPrimary: Colors.grey,
        inactiveColorSecondary: Colors.purple,
      ),
      PersistentBottomNavBarItem(
        icon: Icon(Icons.search),
        title: "Search",
        activeColorPrimary: Colors.teal,
        inactiveColorPrimary: Colors.grey,
        routeAndNavigatorSettings: RouteAndNavigatorSettings(
          initialRoute: '/',
          routes: {
            '/first': (context) => MainScreen2(),
            '/second': (context) => MainScreen3(),
          },
        ),
      ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Navigation Bar Demo')),
      body: PersistentTabView(
        context,
        controller: PersistentTabController(),
        screens: _buildScreens(),
        items: _navBarsItems(),
        handleAndroidBackButtonPress: false,
        selectedTabScreenContext: (context) => currentContext = context,
        onWillPop: (context) async {
          if (Navigator.canPop(currentContext)) {
            Navigator.pop(currentContext);
          } else {
           // Do nothing
          }
          return false;
        },
        navBarStyle: NavBarStyle.style17,
      ),
    );
  }
}
```

If that works in your case, I think I would not introduce a new parameter as it would pollute the `PersistentTabView`

**Comment by DomenicoParisiWeb** [comment]
`Error: A value of type 'BuildContext?' can't be assigned to a variable of type 'BuildContext' because 'BuildContext?' is nullable and 'BuildContext' isn't.`
`selectedTabScreenContext: (context) => **currentContext** = context,`

`Field 'currentContext' should be initialized because its type 'BuildContext' doesn't allow null.`
`BuildContext **currentContext**;`

**Comment by jb3rndt** [comment]
Oh, `currentContext` should be nullable then. I changed it in the example. And it requires another fix in the package which will be released with the next version

**Comment by DomenicoParisiWeb** [comment]
I still get an error, the context must be initialized immediately and not be null.


I have downplayed the example to this:
```
          handleAndroidBackButtonPress: false,
          onWillPop: (context) async {
            return true;
          },
```
But...
`The following _CastError was thrown building PersistentTabView(dirty, state: _PersistentTabViewState#a85e0):
type 'Future<bool>' is not a subtype of type '(() => Future<bool>)?' in type cast`

**Comment by jb3rndt** [comment]
Yep that is the error, it should be fixed with 4.2.5. It just got released, so it should be available soon

**Comment by DomenicoParisiWeb** [comment]
I have updated everything, the persistent error is this:
`error: The argument type 'BuildContext?' can't be assigned to the parameter type 'BuildContext'. (argument_type_not_assignable at [saniday] lib\main.dart:298)`

**Comment by jb3rndt** [comment]
Yep, although it could still throw a null check error so if that is the case, just insert an additional null condition like here: https://github.com/jb3rndt/PersistentBottomNavBarV2/issues/53#issuecomment-1217084808

So I hope your issue is resolved, just reopen if you have further questions
