### ISSUE TITLE
Restore page removed with "pushReplacement"

### ISSUE THREAD

**Issue by DomenicoParisiWeb** [jb3rndt/PersistentBottomNavBarV2#54]
Hello everybody,

My app starts with login.
Once authenticated, I remove the login page with "Navigator.pushReplacement".
When I log out, of course I no longer return to the login page with "Navigator.of (context, rootNavigator: true) .pop ();".
How can I solve this problem?

Many thanks in advance.

**Comment by jb3rndt** [comment]
I would suggest to either push your login page after doing `Navigator.of(context,rootNavigator: .pop();` or to have a page that listens to the login status of the user and builds your homescreen or the login page on every change of the login status.

**Comment by DomenicoParisiWeb** [comment]
I use a generic HomePage (login), and, after logged in, the "persistent navbar" is started.
Now I do this with `pushReplacement`.
I was thinking of using `restorablePushReplacement` but I don't know how to implement it.

**Comment by DomenicoParisiWeb** [comment]
I used a statelesswidget as main widget (with boolean "logged" status), which displays a login widget or the "PersistentTabView" based on the login status.

But now with "pushNewScreenWithRouteSettings" the back button of android no longer goes back, but closes the app.

Help me.

**Comment by jb3rndt** [comment]
Ok nice 👍 I've never heard of `restorablePushReplacement` so I dont know how it works either ^^
