### ISSUE TITLE
PageTransitionAnimation default and duration

### ISSUE THREAD

**Issue by DomenicoParisiWeb** [jb3rndt/PersistentBottomNavBarV2#56]
Is it possible to change this default parameter (which is normally "cupertino")?
`PageTransitionAnimation`

Same question regarding the duration of the animation...

**Comment by jb3rndt** [comment]
Where exactly? You can change the `PageTransitionAnimation` to whatever you want everytime you call one of the navigator functions

**Comment by DomenicoParisiWeb** [comment]
I'll explain:

- Can I use a custom animation?
- Can I manage the duration of the animation?

**Comment by jb3rndt** [comment]
There are three major places where animations are used.
1. The items of some navbar styles are animated (probably not what you are asking for)
2. When a new screen is pushed to the navigator stack
3. When you change from one tab to another

For pushing new screens with one of the navigator functions (`pushNewScreen`, `pushNewScreenWithRouteSettings`, ) to the navigator stack, you can use one animation of the following (the animation duration can **not** be changed):
```dart
enum PageTransitionAnimation {
  cupertino,
  slideRight,
  scale,
  rotate,
  sizeUp,
  fade,
  scaleRotate,
  slideUp
}
```

Regarding the animation when changing tabs: this animation can **not** be changed, although you can change the animation duration with ```
screenTransitionAnimation: ScreenTransitionAnimation(
  animateTabTransition: true,
  curve: Curves.ease,
  duration: Duration(milliseconds: 200),
),
```.

**Comment by DomenicoParisiWeb** [comment]
> ```dart
> enum PageTransitionAnimation {
>   cupertino,
>   slideRight,
>   scale,
>   rotate,
>   sizeUp,
>   fade,
>   scaleRotate,
>   slideUp
> }
> ```
Can I add others, perhaps from other packages?

> ```
> screenTransitionAnimation: ScreenTransitionAnimation(
>   animateTabTransition: true,
>   curve: Curves.ease,
>   duration: Duration(milliseconds: 200),
> ),
> ```
This is the time to switch cards, I refer to: "When a new screen is pushed to the navigator stack".

**Comment by jb3rndt** [comment]
> Can I add others, perhaps from other packages?
You pass a `customPageRoute` to the navigator functions which allows you to pass a customized `PageRouteBuilder`. I just realized that you can change the animation duration this way too.
