### ISSUE TITLE
Display Nav Bar after withNavBar: false

### ISSUE THREAD

**Issue by xxJeevesxx** [jb3rndt/PersistentBottomNavBarV2#59]
Using `pushNewScreen(context, screen: screen, withNavBar: false)` works as intended but from there if I use pushNewScreen again the bottom nav bar is not brought back. Anyway to show the nav bar again while still keeping the Navigation stack so pop will work correctly?

**Comment by jb3rndt** [comment]
Hm thats a tricky thing to do. The only way I imagine it could work, is if you push a new screen (with `withNavBar: true`) but somehow trigger your PersitentTabView to switch `hideNavigationBar` to `true`. And when you push your third page, switch it back to `false`. Do you think that would work in your case?

**Comment by xxJeevesxx** [comment]
Thanks for the suggestion, I didn't even think of that. It does seem to work but the transitions aren't as smooth. Maybe there is a way to fix that. I'll play around with it.
