### ISSUE TITLE
PersistentBottomNavBarItem.onPressed is called with null context before switching tabs

### ISSUE THREAD

**Issue by madmini** [jb3rndt/PersistentBottomNavBarV2#65]
How to reproduce: In the example app select "Built-in style example", then press the plus button. The modal is not opened, and instead an exception is thrown.

The reason is that `PersistentBottomNavBarItem.onPressed` is called with a context of `null`.

Note that when switching to the "Search" tab (or any other) and then back to "Home", the button works as intended.  
Also note that the issue is not with the modal screen itself as the "Push Dynamic/Modal Screen" button works just fine.

**Comment by serraojoao** [comment]
i am currently facing same issue, did you found a solution?

**Comment by madmini** [comment]
Our current workaround is just using the outer context instead, which is provided by some Builder further up the tree. This is sufficient in our use case, but by no means a clean solution.

**Comment by jb3rndt** [comment]
I'll keep an eye on it, dont know how to fix that yet

**Comment by jb3rndt** [comment]
Fixed with Version 5
