### ISSUE TITLE
Switching to a nav tab that already loaded does not refresh content

### ISSUE THREAD

**Issue by kbessemer** [jb3rndt/PersistentBottomNavBarV2#66]
The issue is that when I start on nav tab index 1, and then switch to index 2 for the first time it runs the InitState function and builds the screen correctly, but if I switch back to index 1 it does not run InitState again and rebuild the screens content. Same with if I switch back to index 2.

Desired Behavior:
I'd like it to refresh the content on the screen every time I click one of the bottom nav bar items, even if I have already loaded that screen once.

**Comment by jb3rndt** [comment]
Setting `stateManagement: false` on your `PersistentTabView` should fix that

**Comment by serraojoao** [comment]
@kbessemer did it work for you? I've just tried and did not had the expected behavior

**Comment by jb3rndt** [comment]
Can you provide a small example and show what is not working?

**Comment by serraojoao** [comment]
the pages were just not refreshing every time i go into them after setting the stateManagement to false. At the moment I replaced the package and do not have it currently implemented on the project, thanks for supporting!

**Comment by jb3rndt** [comment]
Ok, Im gonna close this for now
