### ISSUE TITLE
FloatingActionButton command gives error

### ISSUE THREAD

**Issue by abdulsamadv** [jb3rndt/PersistentBottomNavBarV2#73]
I'm using below code, but gets "Hot Restart Error DevFS synchronization failed" error. If i remove floatingActionButton code snippet then no error. Can someone help me?

------------------------------------
```
import 'package:flutter/material.dart';

void main() =>  runApp(MaterialApp(
    home: Scaffold(
appBar: AppBar(
  title: Text('My First Apps'),
  centerTitle: true,

    ),
      body: Center(
        child: Text('Hi Abdul Samada'),
      ),
      floatingActionButton: FloatingActionButton(
        label: Text('Click'),
      ),

  ),
));
```
--------------------------------------

**Comment by jb3rndt** [comment]
Did you completely stop and restart your application? If the issue persists after that, can you provide the whole stack trace?
