### ISSUE TITLE
initState hitting multiple times

### ISSUE THREAD

**Issue by Shubham-Narkhede** [jb3rndt/PersistentBottomNavBarV2#74]
I want to reload the api when we change the tab. I set state management to False but it calls every screen so automatically my API hitting multiple times. Is there any solution on it

**Comment by jb3rndt** [comment]
Hi, please try the steps I described here: https://github.com/jb3rndt/PersistentBottomNavBarV2/issues/23#issuecomment-1328339124
Let me know if that solved your problem :)
