### ISSUE TITLE
Material style pageTransitionAnimation is missing. 

### ISSUE THREAD

**Issue by jurrdb** [jb3rndt/PersistentBottomNavBarV2#82]
The page transitions can be done in Cupertino style and in a number of other styles. However, there is no way of using the Material style page transition.

**Comment by jb3rndt** [comment]
Which case are you referring to exactly? If you refer to using the navigator functions to push new pages, you can always pass a `pageTransitionAnimation` where you can also pass a Material page transition.

**Comment by lyngbach** [comment]
How would you go about doing that?

**Comment by jb3rndt** [comment]
You are right, it is missing. In Version 5, which is currently in Beta, there is `PageTransitionAnimation.platform`, which effectively uses the Material Page Route (which in turn uses the Material animation on android and the cupertino animation on iOS, so it does the correct thing for each platform.
Anyway, feel free to switch to the beta.
If you cant, here is a code snipped to do it in the current version 4.

```
pushDynamicScreen(
  context,
  screen: MaterialPageRoute(
    builder: (context) => MainScreen2(),
  ),
  withNavBar: false,
);
```
