### ISSUE TITLE
Update active bar item when navigating ?

### ISSUE THREAD

**Issue by quen09t** [jb3rndt/PersistentBottomNavBarV2#84]
Hello, thank for maintaining this package! 
Is there any documentation on how to navigate programaticaly to a specific bottom bar item ?
Thanks

**Comment by jb3rndt** [comment]
Hi, you can pass a custom `PersistentTabController` to your `PersistentTabView` and anywhere in your code, you can use `controller.jumpToTab(x)`.

**Comment by quen09t** [comment]
work like a charm, thanks you
