### ISSUE TITLE
Android Back button

### ISSUE THREAD

**Issue by azerturk** [jb3rndt/PersistentBottomNavBarV2#85]
I only set

handleAndroidBackButtonPress: false,
stateManagement: false,
navBarHeight: state.heightBottomBar,

When i set the handleAndroidBackButtonPress: true, it is working but forexample firstly height is 80 on homepage when i first navigate to the other page then i set the height to 0 then on back i set it to 80 again. But it is working only with my custom back buttons actions. Android back button WillPopScope never fires. With setting handleAndroidBackButtonPress: false, on same scenario this time my custom button also works but when clicking Android back button for every screen it is exitting the app but WillPopScope never fire again.
I used the first version it is the nearly same scenario only it shows errors this v2 is exitting the app.

**Comment by azerturk** [comment]
because in persistentnavbar 1 when i used i read in their issue page that if you set the navbar false then true will not work so i set height manually in home page i have 4 tabs then i navigate to the login screen with 0 height.

context.read<MyFirstAppState>().setHeightTest();
                  pushNewScreenWithRouteSettings(
                    context,
                    settings: RouteSettings(name: AppRoute.login),
                    screen: LoginScreen(),
                    withNavBar: true,
                    pageTransitionAnimation: PageTransitionAnimation.fade,
                  );

persistentnavbar 2 changed this? i didn't test it but not only for this scenario maybe i want to handle android back button with setting handleAndroidBackButtonPress: false not working. Thanks.

**Comment by azerturk** [comment]
height also work in v2 my problem is android back button but if you prefer other solution it is okay for me. Currently i want only tabs on some pages but on general navigations and back button it is broken.

**Comment by jb3rndt** [comment]
I dont know if I understand correctly: When tapping the Android back Button, your custom `WillPopScope` is not executed? You can solve that by setting `handleAndroidBackButtonPress: false` and use the `onWillPop` parameter. You can put your logic in that callback and it will be executed.

**Comment by azerturk** [comment]
Yes i did this and other scenarios. Okay i am going to put thsi package on fresh app and test it. If it is working my problem is related maybe other things. Currently when i tap back button with false option in any screen app is closed.

**Comment by jb3rndt** [comment]
Ok, yes this is expected: If you have `handleAndroidBackButtonPress: false` **and** `onWillPop: null`, the app will close. You need to have either `handleAndroidBackButtonPress: true` **or** `onWillPop: (context) => Future.value(false)`.

**Comment by azerturk** [comment]
i think you don't understand me i want to show alert on back button and also set height but it is not working

**Comment by azerturk** [comment]
Okay. i set this values and it seems working: But i think i am doing wrong. Can you prefer other ways?

withNavBar: true i can't handle onWillPop not fired.

handleAndroidBackButtonPress: true, -- this work also with false because i return true from  onWillPop

stateManagement: false,

navBarHeight: state.heightBottomBar, -- with provider i set it on all navigation and back default is 80

withNavBar: false, -- all screen navigation only return back to home navigation is true

On Home screen:

context.read<MyFirstAppState>().setHeightTest(); - set to zero
                  pushNewScreenWithRouteSettings(
                    context,
                    settings: RouteSettings(name: AppRoute.login),
                    screen: LoginScreen(),
                    withNavBar: false,
                    pageTransitionAnimation: PageTransitionAnimation.fade,
                  );

on Login Screen:

Android Back
onWillPop: () {
        context.read<MyFirstAppState>().setHeight(); - set 80
        return Future.value(true);
      },
Custom Back
pushNewScreenWithRouteSettings(
                              context,
                              settings: RouteSettings(name: AppRoute.home),
                              screen: HomeScreen(),
                              withNavBar: true,
                              pageTransitionAnimation:
                                  PageTransitionAnimation.fade,
                            ).then((value) =>
                                context.read<MyFirstAppState>().setHeight()); - set to 80

**Comment by jb3rndt** [comment]
Why do you need to set the navbar height to 0 when the Login Screen is pushed from the homescreen?

**Comment by azerturk** [comment]
> Why do you need to set the navbar height to 0 when the Login Screen is pushed from the homescreen?

When i set to withNavBar: false on other screens then it is not possible to set it to the true. So i used the height

**Comment by jb3rndt** [comment]
It seems to be working for you? So I'm closing this issue now. If there is something else feel free to reopen this one or open another one.
