### ISSUE TITLE
[5.0.0-beta.4] Black bar beneath BottomNavigationBar

### ISSUE THREAD

**Issue by DynxstyGIT** [jb3rndt/PersistentBottomNavBarV2#88]
Hey, I just upgraded to the newest beta and noticed a black bar beneath my bottom navigation bar - despite the backgrounColor being set to white.

<img width="336" alt="Screenshot 2023-02-16 at 16 42 52" src="https://user-images.githubusercontent.com/48297101/219415352-2314d37c-d00c-4522-9d45-4a394d949bfe.png">

My setup looks something like this:

```dart
@override
  Widget build(BuildContext context) {
    final List<PersistentTabConfig> tabs = [...]
    return SafeArea(
      top: false,
      child: PersistentTabView(
        controller: _tabController,
        tabs: tabs,
        drawer: _buildDrawer(),
        drawerEdgeDragWidth: MediaQuery.of(context).size.width / 3,
        navBarBuilder: (config) {
          return ButtonBottomNavigationBar(
              config: config,
              selectedIndex: _tabController.index
             );
        },
      ),
    );
  }
```

**Comment by DynxstyGIT** [comment]
I got it fixed by surrounding the SafeArea with another Scaffold - As its noted **_not_** to use another Scaffold, i'll leave this open, as this may be a potential bug then

**Comment by DynxstyGIT** [comment]
Okay, still got some issues tho: somehow, the Drawers' shadow clips beneath the navbar. Is there a way to extend the navbar to the bottom? This would probably also fix the black bar thingy.

<img width="335" alt="Screenshot 2023-02-16 at 16 37 45" src="https://user-images.githubusercontent.com/48297101/219471826-e5c39c3e-9745-47f1-b8be-58493a4fecac.png">

(Setting the `elevation` to `0` works, but isnt really ideal ig)

**Comment by ZahraVe** [comment]
@DynxstyGIT You can try to remove `SafeArea` wrapped around `PersistentTabView` and instead set `confineInSafeArea: true` inside the `PersistentTabView`.

**Comment by DynxstyGIT** [comment]
Hey, thanks for the reply - I can't find such parameter in the current beta. Was it removed?

**Comment by jb3rndt** [comment]
It got renamed to `avoidBottomPadding`. I'm curious if that solves your safearea issue
