### ISSUE TITLE
styles 15 and 16 throwing 'unexpected null value'

### ISSUE THREAD

**Issue by pdaniel37** [jb3rndt/PersistentBottomNavBarV2#9]
all styles working, except 15 and 16
`The following TypeErrorImpl was thrown building AnimatedBuilder(animation: AnimationController#4c4a8(⏭ 1.000; paused)➩CurveTween(curve: Cubic(0.25, 0.10, 0.25, 1.00))➩Tween<double>(375 → 0)➩0, dirty, state: _AnimatedState#74505):
Unexpected null value.`
`When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
packages/persistent_bottom_nav_bar_v2/persistent-tab-view.widget.dart 503:79                                                   [_buildScreen]
packages/persistent_bottom_nav_bar_v2/persistent-tab-view.widget.dart 612:22                                                   <fn>
packages/persistent_bottom_nav_bar_v2/models/persistent-nav-bar-scaffold.widget.dart 414:57                                    <fn>`

my code is the basic implementation
``` dart
Widget build(BuildContext context) {
  return PersistentTabView(
    context,
    controller: controller!,
    screens: _buildScreens(),
    items: _navBarsItems(),
    resizeToAvoidBottomInset: true,
    navBarStyle: NavBarStyle.style16,
    backgroundColor: const Color(0xFFEFEFEF),
    itemAnimationProperties: const ItemAnimationProperties(
      duration: Duration(milliseconds: 200),
      curve: Curves.ease,
    ),
    screenTransitionAnimation: const ScreenTransitionAnimation(
      animateTabTransition: true,
      curve: Curves.ease,
      duration: Duration(milliseconds: 200),
    ),
  );
}
```

**Comment by jb3rndt** [comment]
Should be fixed with version 4.1.5
