### ISSUE TITLE
[5.0.0-beta.5] Items flickering when using `jumpToTab`

### ISSUE THREAD

**Issue by DynxstyGIT** [jb3rndt/PersistentBottomNavBarV2#90]
Hello, 
I've upgraded to the latest beta and noticed some weird flickering when switching to different tabs. Is there a way to prevent this? I've simply used the index setter on the controller before

https://user-images.githubusercontent.com/48297101/223238882-a83fbf75-ef48-41b6-ac4b-79df06b1a729.mov

**Comment by jb3rndt** [comment]
Looks strange, can you post a minimal example of the issue so I can try it out?

**Comment by jb3rndt** [comment]
Update: I found the reason and I'm trying to fix it

**Comment by DynxstyGIT** [comment]
Sorry, haven't seen your initial response! Thanks fixing this! 🙏
