### ISSUE TITLE
Enforcing screen initialization on first launch in App

### ISSUE THREAD

**Issue by iBelow** [jb3rndt/PersistentBottomNavBarV2#93]
Hey there, how can I force all screens to initialize on the first launch? The issue is that I have a screen with a shopping cart (**using bloc + provider**), but I can't get the bloc instance to pass the number of items to the counter in the icon until I at least enter that screen once.

**Comment by jb3rndt** [comment]
This would require every screen to be built once, which would heavily reduce perfomance at app start. I would suggest that you initialize all your blocs and providers that are needed in different places, before the MaterialApp (or somewhere else in the root of your app), so they are available everywhere.

**Comment by iBelow** [comment]
@jb3rndt I did just that, instances of the bloc are created before the MaterialApp, and initState is not called until the necessary page is accessed. Therefore, the bloc will not be loaded anywhere until the page is opened at least once.

**Comment by iBelow** [comment]
so, i'm fix it with bloc-listener, thanx
