### ISSUE TITLE
WillPopScope - Android back button - Inherit from child

### ISSUE THREAD

**Issue by kbessemer** [jb3rndt/PersistentBottomNavBarV2#94]
**Is your feature request related to a problem? Please describe.**
The problem lies with Android phones having a back button, when the PersistentTabView screen is loaded the Android back button treats the PersistentTabView as the file to listen to what the back button does, instead of the child - meaning the PersistentBottomNavBarItem (screen index of child).

**Describe the solution you'd like**
I'd like PersistentTabView to look at the child's code to see what WillPopScope will do.

**Describe alternatives you've considered**
I implemented WillPopScope in the PersistentTabView, and was able to somewhat control the behavior based on what the current tab index is. But this did not work for every screen, because once you navigate from the initial screen (starting tab index), the WillPopScope is taken from the children. But on the first child render of PersistentTabView, WillPopScope is read from the PersistentTabView class/file.

**Additional context**

**Comment by jb3rndt** [comment]
Just to make sure I understand correct: When the android back button is tapped, you always need `onWillPop` (which is passed to `PersistentTabView`) to be invoked, no matter which tab you are on, instead of first switching to the first tab?

You can set `handleAndroidBackButtonPress: false`, then the `onWillPop` callback will always be called when the android back button is tapped.
Let me know if that solves it :)

**Comment by jb3rndt** [comment]
Did you make sure to give `onWillPop` a callback like so?
```
onWillPop: () {
  print("onWillPop called);
}
```
Additionally, `onWillPop` is only expected to be executed when you have no pages pushed to your root navigator (i.e. as long as you can see your navigation bar).
If it still doesnt work, can you post a minimal code example so I can reproduce it?

**Comment by Tarhex** [comment]
Still doesn't work, I will post the code I am using.

**Comment by jb3rndt** [comment]
Seems like there is an issue with the context being null, right? It'll probably take me a while to fix that. If you come up with a solution in the mean time feel free to share.

**Comment by Tarhex** [comment]
Let me explain what I am doing. 

So, I have an Onboarding page that opens immediately the app loads. By tapping on Next, a Company page is pushed to replace (pushReplacement) the Onboarding page. On the Company page, you then tap on a button to move to the Main Screen (the Company is replaced by the Main Screen page). The Main Screen contains the `PersistentTabView`.

**Comment by jb3rndt** [comment]
Ok, what exactly does not work for you there? Can you please open a new issue for that? It does not seem to relate to this one.

**Comment by Tarhex** [comment]
So, I had to start the app from scratch again and it worked. Thanks for the reply.
