### ISSUE TITLE
Navigating to non-adjacent tabs briefly animates towards adjacent tabs in the process.

### ISSUE THREAD

**Issue by deezee30** [jb3rndt/PersistentBottomNavBarV2#97]
**Describe the bug**
When navigating to a tab that isn't indexed immediately to the left or the right of the selected tab, the navigator almost always briefly jumps between the intermediate (not-clicked) tabs in random order. In the end the navigator always ends up in the desired tab, but in the process it causes the tab views to build, which causes a lot of building and lags the navigation process. See the screenshot for a visual demonstration.

Navigating to a tab indexed immediately to the left or the right of the selected tab doesn't cause this issue.

**To Reproduce**
1. Set up the tab view using `PersistentTabView` (not `PersistentTabViewScaffold`) and follow documentation.
2. Set up at least 3 tabs (I currently have 4).
3. Navigate from index 0 to 3.

**Expected behavior**
Smooth navigation only to the desired tab without flicker.

**Screenshots**
<img src="https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/1367015/5cca03b2-ed88-49f2-ab8d-32a3d215121a" width="400"/>

**Smartphone:**
 - Device: Emulated Pixel 4
 - OS: Android 12 API 33

**Dev Env:**
 - Flutter: stable 3.7.12
 - persistent_bottom_nav_bar_v2: 5.0.0-beta.5

**Comment by deezee30** [comment]
Actually if you log the index of the tab being changed, you do indeed see tabs changing in a random order.

Changing from 0 to 3: 3, 1, 2, 3
Changing from 3 to 0: 0, 1, 0
Changing from 0 to 3 (again): 3, 2, 3
Changing from 3 to 0 (again): 0

So not only are they random, but they also randomly vary in the amount of intermediary tabs they skip to.

Yes, the behaviour seems to be the same during testing with `gestureNavigationEnabled` set to `true` and `false`.

Thanks for checking this out!

**Comment by rishuriya** [comment]
@jb3rndt is this fixed?? because i m still getting this behaviour

**Comment by jb3rndt** [comment]
It should be. Make sure you are using `gestureNavigationEnabled: false`. Which version of the package are you using? This only applies to v5.x.x. Please also provide a minimal example (may be based on the example app of this package).
