### ISSUE TITLE
backgroundColor doesn't seem to work

### ISSUE THREAD

**Issue by xxJeevesxx** [jb3rndt/PersistentBottomNavBarV2#99]
**Describe the bug**
Setting `backgroundColor` on the `PersistentTabView` doesn't seem to have an affect.

**To Reproduce**
1. Set `backgroundColor: Colors.red` on the `PersistentTabView`.

**Expected behavior**
The color of the nav bar to change.

**Screenshots**
![Screenshot 2023-05-16 at 11 09 41 AM](https://github.com/jb3rndt/PersistentBottomNavBarV2/assets/3445444/dbac7652-dccc-4967-8d57-4af553cd85b1)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1 (a)

**Smartphone (please complete the following information):**
 - Device: iPhone SE (3rd gen)
- OS: iOS 16.4

**Additional context**
I'm probably just missing something simple but I can't figure out what.

**Comment by jb3rndt** [comment]
Ah the docs are outdated for that parameter. The `backgroundColor` changes the background of the whole tab view, so if you would have any transparent places in your tabs, the color would be seen there. To change the color of your navbar, pass a `NavBarDecoration` to your `Style6BottomNavBar` like so:

```dart
...
navBarBuilder: (p0) => Style6BottomNavBar(
  navBarConfig: p0,
  navBarDecoration: const NavBarDecoration(
    color: Colors.red,
  ),
),
...
```

**Comment by xxJeevesxx** [comment]
Ah, that makes sense. Perfect, Thank you!!
